# Generated by Django 4.2.2 on 2023-06-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees_structure", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="hired",
            field=models.DateField(blank=True, null=True),
        ),
    ]
