# Generated by Django 4.2.2 on 2023-06-12 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employees_structure", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="show_subordinates",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
